const copyrightText=document.querySelector(".copyright"),date=(new Date).getFullYear();copyrightText.textContent=`\u00a9 Copyright 2023 - ${date}, Frank's Furters`;var {OverlayScrollbars,ScrollbarsHidingPlugin,SizeObserverPlugin,ClickScrollPlugin}=OverlayScrollbarsGlobal;
const osInstance=OverlayScrollbars(document.body,{}),navOpenBTN=document.querySelector(".nav-open-btn"),navCloseBTN=document.querySelector(".nav-close-btn"),mainNav=document.querySelector(".main-nav"),navBackground=document.querySelector(".nav-background"),mainNavItems=document.querySelectorAll(".main-nav-item"),nonNavItems=document.querySelectorAll("button:not(.main-nav-item), a:not(.main-nav-item), iframe:not(.main-nav-item)");let navSizeTimeout=!1,navTabTimeout=!1;
899>=window.innerWidth&&mainNavItems.forEach(a=>{a.setAttribute("tabindex",-1)});window.addEventListener("resize",navTabDebounce);function navTabChecker(){899>=window.innerWidth?mainNavItems.forEach(a=>{a.setAttribute("tabindex",-1)}):mainNavItems.forEach(a=>{a.removeAttribute("tabindex")})}function navTabDebounce(){clearTimeout(navTabTimeout);navTabTimeout=setTimeout(navTabChecker,300)}function navSizeChecker(){900<=window.innerWidth&&closeNav()}
function navSizeDebounce(){clearTimeout(navSizeTimeout);navSizeTimeout=setTimeout(navSizeChecker,300)}function mainNavControls(a){"Escape"===a.code&&closeNav()}
function openNav(){mainNav.classList.add("main-nav-open");navBackground.classList.add("nav-background-open");navCloseBTN.classList.add("nav-close-btn-open");navBackground.addEventListener("click",closeNav);mainNavItems.forEach(a=>{a.addEventListener("click",closeNav)});document.documentElement.classList.add("stop-scrolling");document.body.classList.add("stop-scrolling");window.addEventListener("resize",navSizeDebounce);window.removeEventListener("resize",navTabDebounce);mainNavItems.forEach(a=>{a.removeAttribute("tabindex")});
nonNavItems.forEach(a=>{a.setAttribute("tabindex",-1)});window.addEventListener("keydown",mainNavControls)}
function closeNav(){mainNav.classList.remove("main-nav-open");navBackground.classList.remove("nav-background-open");navCloseBTN.classList.remove("nav-close-btn-open");navBackground.addEventListener("click",closeNav);document.documentElement.classList.remove("stop-scrolling");document.body.classList.remove("stop-scrolling");window.removeEventListener("resize",navSizeDebounce);window.addEventListener("resize",navTabDebounce);899>=window.innerWidth?mainNavItems.forEach(a=>{a.setAttribute("tabindex",
-1)}):mainNavItems.forEach(a=>{a.removeAttribute("tabindex")});nonNavItems.forEach(a=>{a.removeAttribute("tabindex")});window.removeEventListener("keydown",mainNavControls)}navOpenBTN.addEventListener("click",openNav);navCloseBTN.addEventListener("click",closeNav);
const swiper=new Swiper(".swiper",{direction:"horizontal",loop:!1,navigation:{nextEl:".form-nav-next",prevEl:".form-nav-prev"},scrollbar:{el:".swiper-scrollbar"},keyboard:{enabled:!0},allowTouchMove:!1}),formPageOne={firstName:document.getElementById("fname"),middleName:document.getElementById("mname"),lastName:document.getElementById("lname"),birthDate:document.getElementById("birth-date"),gender:document.getElementsByName("gender")},formPageTwo={homeStreet:document.getElementById("home-street"),
homeAptSuite:document.getElementById("home-apt-suite"),homeCity:document.getElementById("home-city"),homeState:document.getElementById("home-state"),homeZipCode:document.getElementById("home-zipcode"),socialSecurity:document.getElementById("applicant-ssn")},formPageThree={contactTelephone:document.getElementById("telephone"),email:document.getElementById("email"),preferredContact:document.getElementsByName("preferred-contact-method"),contactTimeStart:document.getElementById("contact-time-start"),
contactTimeEnd:document.getElementById("contact-time-end")},formPageFour={usCitizenStatus:document.getElementsByName("us-citizen-status"),usWorkStatus:document.getElementsByName("us-work-status"),workedPriorStatus:document.getElementsByName("worked-here-prior-status"),priorEmploymentStart:document.getElementById("prior-employment-start"),priorEmploymentEnd:document.getElementById("prior-employment-end"),felonyStatus:document.getElementsByName("felony-status")},formPageFive={highSchoolName:document.getElementById("high-school-name"),
highSchoolCity:document.getElementById("high-school-city"),highSchoolState:document.getElementById("high-school-state"),highSchoolStart:document.getElementById("high-school-start"),highSchoolEnd:document.getElementById("high-school-end"),highSchoolGraduation:document.getElementsByName("high-school-graduation-status"),highSchoolDiploma:document.getElementById("high-school-diploma-type"),gedStatus:document.getElementsByName("ged-status")},formPageSix={collegeName:document.getElementById("college-name"),
collegeCity:document.getElementById("college-city"),collegeState:document.getElementById("college-state"),collegeStart:document.getElementById("college-start"),collegeEnd:document.getElementById("college-end"),collegeGraduation:document.getElementsByName("college-graduation-status"),collegeDiploma:document.getElementById("college-degree-type")},formPageSeven={employerOneName:document.getElementById("employer-one-name"),employerOneTelephone:document.getElementById("employer-one-telephone"),employerOneStreet:document.getElementById("employer-one-street"),
employerOneCity:document.getElementById("employer-one-city"),employerOneState:document.getElementById("employer-one-state"),employerOneZipCode:document.getElementById("employer-one-zipcode"),employerOnePosition:document.getElementById("employer-one-position"),employerOneStart:document.getElementById("employer-one-start"),employerOneEnd:document.getElementById("employer-one-end")},formPageEight={employerTwoName:document.getElementById("employer-two-name"),employerTwoTelephone:document.getElementById("employer-two-telephone"),
employerTwoStreet:document.getElementById("employer-two-street"),employerTwoCity:document.getElementById("employer-two-city"),employerTwoState:document.getElementById("employer-two-state"),employerTwoZipCode:document.getElementById("employer-two-zipcode"),employerTwoPosition:document.getElementById("employer-two-position"),employerTwoStart:document.getElementById("employer-two-start"),employerTwoEnd:document.getElementById("employer-two-end")},formPageNine={referenceOneFirstName:document.getElementById("reference-one-fname"),
referenceOneLastName:document.getElementById("reference-one-lname"),referenceOneRelationship:document.getElementById("reference-one-relationship"),referenceOneTelephone:document.getElementById("reference-one-telephone")},formPageTen={referenceTwoFirstName:document.getElementById("reference-two-fname"),referenceTwoLastName:document.getElementById("reference-two-lname"),referenceTwoRelationship:document.getElementById("reference-two-relationship"),referenceTwoTelephone:document.getElementById("reference-two-telephone")},
formPageEleven={qualifications:document.getElementById("qualifications")};function characterCountFinder(a){a=a.target;a.nextElementSibling.firstElementChild.textContent=`${a.value.length}`}const currentDate=new Date,maxBirthDate=`${currentDate.getFullYear()-18}-${("0"+(currentDate.getMonth()+1)).slice(-2)}-${("0"+currentDate.getDate()).slice(-2)}`;formPageOne.birthDate.setAttribute("max",maxBirthDate);function checkRadioValue(a){for(var b=0;b<a.length;b++)if(a[b].checked)return a[b].value}
function repeatString(a,b){let c="";for(;0<b;)c+=a,b--;return c}
const arrayOfStates="Alabama;Alaska;Arizona;Arkansas;California;Colorado;Connecticut;Delaware;Florida;Georgia;Hawaii;Idaho;Illinois;Indiana;Iowa;Kansas;Kentucky;Louisiana;Maine;Maryland;Massachusetts;Michigan;Minnesota;Mississippi;Missouri;Montana;Nebraska;Nevada;New Hampshire;New Jersey;New Mexico;New York;North Carolina;North Dakota;Ohio;Oklahoma;Oregon;Pennsylvania;Rhode Island;South Carolina;South Dakota;Tennessee;Texas;Utah;Vermont;Virginia;Washington;West Virginia;Wisconsin;Wyoming".split(";"),isEmptyPattern=
/([^\s])/,personNamePattern=/^[a-zA-Z'-]{1,15}$/,properDatePattern=/^\d{4}[-](0[1-9]|1[012])[-](0[1-9]|[12][0-9]|3[01])$/,addressPattern=/^[^*,.()":;']+$/,addressLimit=/^.{1,45}$/,cityPattern=/^[a-zA-Z1-9'., -\/]{1,28}$/,zipCodePattern=/^\d{5}$/,zipCodeExtendedPattern=/^\d{5}[-]\d{4}$/,socialSecurityPattern=/^\d{9}$/,socialSecurityExtendedPattern=/^\d{3}[-]\d{2}[-]\d{4}$/,telephonePattern=/^\d{10}$/,telephoneExtendedPattern=/^[(]\d{3}[)]\d{3}[-]\d{4}$/;
function validatePageContent(a){return!0===a}let pageOneValues=[],pageTwoValues=[],pageThreeValues=[],pageFourValues=[],pageFiveValues=[],pageSixValues=[],pageSevenValues=[],pageEightValues=[],pageNineValues=[],pageTenValues=[],pageElevenValues=[];function validateBirthDate(){properDatePattern.test(formPageOne.birthDate.value)&&new Date(formPageOne.birthDate.value)<=new Date(maxBirthDate)?pageOneValues.push(!0):pageOneValues.push(!1)}
function validatePersonName(a,b,c="Not Required"){var d=`^(!?${repeatString(".*'",2)}).*$`;d=new RegExp(d);var e=`^(!?${repeatString(".*-",2)}).*$`;e=new RegExp(e);"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):!0===personNamePattern.test(a)&&!1===d.test(a)&&!1===e.test(a)?b.push(!0):b.push(!1)}function validateMultipleChoice(a,b,c,d="Not Required"){"Not Required"!==d||""!==a&&void 0!==a?c.includes(a)?b.push(!0):b.push(!1):b.push(!0)}
function validateStreetAddress(a,b,c="Not Required"){"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):addressPattern.test(a)&&addressLimit.test(a)&&!0===isEmptyPattern.test(a)?b.push(!0):b.push(!1)}
function validateCity(a,b,c="Not Required"){var d=`^(!?${repeatString(".*'",2)}).*$`;d=new RegExp(d);var e=`^(!?${repeatString(".*\\.",2)}).*$`;e=new RegExp(e);var f=`^(!?${repeatString(".*,",2)}).*$`;f=new RegExp(f);var g=`^(!?${repeatString(".* ",2)}).*$`;g=new RegExp(g);var h=`^(!?${repeatString(".*-",2)}).*$`;h=new RegExp(h);var k=`^(!?${repeatString(".*\\/",2)}).*$`;k=new RegExp(k);"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):!0===cityPattern.test(a)&&!1===d.test(a)&&!1===e.test(a)&&
!1===f.test(a)&&!1===g.test(a)&&!1===h.test(a)&&!1===k.test(a)?b.push(!0):b.push(!1)}function validateZipCode(a,b,c="Not Required"){"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):zipCodePattern.test(a)||zipCodeExtendedPattern.test(a)?b.push(!0):b.push(!1)}function validateSocialSecurity(a,b,c="Not Required"){"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):socialSecurityPattern.test(a)||socialSecurityExtendedPattern.test(a)?b.push(!0):b.push(!1)}
function validateTelephone(a,b,c="Not Required"){"Not Required"===c&&!1===isEmptyPattern.test(a)?b.push(!0):socialSecurityPattern.test(a)||socialSecurityExtendedPattern.test(a)?b.push(!0):b.push(!1)}
function validatePageOne(){swiper.enabled=!1;validatePersonName(formPageOne.firstName.value,pageOneValues,"Required");validatePersonName(formPageOne.middleName.value,pageOneValues);validatePersonName(formPageOne.lastName.value,pageOneValues,"Required");validateBirthDate();validateMultipleChoice(checkRadioValue(formPageOne.gender),pageOneValues,["Male","Female","Required"]);pageOneValues.every(validatePageContent)&&(swiper.enabled=!0);pageOneValues=[]}
function validatePageTwo(){swiper.enabled=!1;validateStreetAddress(formPageTwo.homeStreet.value,pageTwoValues,"Required");validateStreetAddress(formPageTwo.homeAptSuite.value,pageTwoValues);validateCity(formPageTwo.homeCity.value,pageTwoValues,"Required");validateMultipleChoice(formPageTwo.homeState.value,pageTwoValues,arrayOfStates,"Required");validateZipCode(formPageTwo.homeZipCode.value,pageTwoValues,"Required");validateSocialSecurity(formPageTwo.socialSecurity.value,pageTwoValues,"Required");
pageTwoValues.every(validatePageContent)&&(swiper.enabled=!0);pageTwoValues=[]}function validatePageThree(){console.log(pageThreeValues);console.log(pageThreeValues);pageThreeValues.every(validatePageContent)&&(swiper.enabled=!0);pageThreeValues=[]};
